### ISSUE TITLE
Cannot run the emu - what is the exact path for roms directory?

### ISSUE THREAD

**Issue by kdrzazga** [jdewald/qjnes#2]
Hi,

   I've placed basic, characters, kernal files under **...\qjnes\src\java\roms**  path,but during the start they cannot be found. Should a different path be used?

Besides, 
I took these 3 files from VICE emulator and changed their names respectively. Will that work, or I need other, specific files? If so, where can I obtain them?

**Comment by jdewald** [comment]
I have not run it as a C64 emulator in awhile, I will try and update
directions. Thanks for the report!

**Comment by jdewald** [comment]
You would generally place them eith the "roms" directory as a sibling of
"src", that may do the trick for you

**Comment by jdewald** [comment]
Ok I have just confirmed that if you place the appropriate files in "roms" directory you should be good. It uses the current file path (rather than classpath) to locate them. Renaming *should* work, as I don't believe I make any assumptions about the content of the ROMs. 

So from a checkout of the code:

    $ ls

    IDEAS			LICENSE			NOTES			build.xml		instructions.log	nes.properties		smb.nes
    INSTALL			LINKS			ThirdParty		classes			lib			roms			src

    $ls roms 
    basic.901226-01.bin		characters.901225-01.bin	kernal.901227-03.bin

If you did want to change what files it looks for that's in

[https://github.com/jdewald/qjnes/blob/master/src/java/org/fortytwo/c64/Emulator.java](Emulator.java)

Obviously would have been better had I made those be configuration properties, but I think that aspect of the code was written before I knew any better :)

**Comment by kdrzazga** [comment]
works! 
thx
