### ISSUE TITLE
Why does readRegister() method in MOS6502Emulator returns int instead of short?

### ISSUE THREAD

**Issue by kdrzazga** [jdewald/qjnes#7]
The biggest register in C64 is Program Counter with 16 bits. In this case a 16-bit short would be better than 32 bit int. 

Is there a threat I could break something, if I change it?

**Comment by kdrzazga** [comment]
The same applies to Memory::write(int location, int val);  
Why not Memory::write(short location, byte val); ?

**Comment by jdewald** [comment]
I honestly don't recall the reason I used `int` rather than `short` (that was probably one of the first decisions I made about 12 years ago or whenever it was). Likely is because in theory there is nothing inherently 16-bit about the code-level interfaces. It just happens that the things being emulated are 8 and 16-bit. It's also possible I wasn't aware of `short` at the time ;)

I would expect that it's *probably* safe to convert to `short`, and you can see if everything still works. But I'm not sure it's worth the effort though unless there's a specific advantage you think would be gained.

**Comment by kdrzazga** [comment]
It's a thing I could try when the code will be highly covered with unit tests, to make sure nothing was broken. I'll postpone this for later. Thx for explanation...
